import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { ThemeProvider } from '@/components/ui/providers/ThemeProvider';
import { getServerSession } from 'next-auth';
import { SessionProvider } from 'next-auth/react';
import SessionProviderWrapper from '@/components/custom/SessionProvideWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <SessionProviderWrapper session={session!}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <body className={`${inter.className} h-screen w-full`}>
            <Toaster />
            <main>{children}</main>
          </body>
        </ThemeProvider>
      </SessionProviderWrapper>
    </html>
  );
}
