import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { ThemeProvider } from '@/components/ui/providers/ThemeProvider';
import { getServerSession } from 'next-auth';
import SessionProviderWrapper from '@/components/ui/providers/SessionProvideWrapper';
import QueryClientProviderWrapper from '@/components/ui/providers/QueryClientProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <SessionProviderWrapper session={session!}>
        <QueryClientProviderWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <body
              className={`${manrope.className} h-screen w-screen overflow-x-hidden`}
            >
              <ReactQueryDevtools initialIsOpen={false} /> <Toaster />
              <main className="size-full">{children}</main>
            </body>
          </ThemeProvider>
        </QueryClientProviderWrapper>
      </SessionProviderWrapper>
    </html>
  );
}
