import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import Providers from './Providers';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  modals,
}: Readonly<{
  children: React.ReactNode;
  modals: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${manrope.className} overflow-x-hidden`}>
          <ReactQueryDevtools initialIsOpen={false} />
          <Toaster />
          {children}
          {modals}
        </body>
      </Providers>
    </html>
  );
}
